/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { Merchant, Offer, Transaction } from './types';

export const MERCHANTS: Merchant[] = [
  { id: '1', name: 'Amazon', logo: '🛒', category: 'Electronics' },
  { id: '2', name: 'Nike', logo: '👟', category: 'Fashion' },
  { id: '3', name: 'Expedia', logo: '✈️', category: 'Travel' },
  { id: '4', name: 'Apple', logo: '🍎', category: 'Electronics' },
  { id: '5', name: 'Zalando', logo: '👗', category: 'Fashion' },
  { id: '6', name: 'Hotels.com', logo: '🏨', category: 'Travel' },
  { id: '7', name: 'Sephora', logo: '💄', category: 'Lifestyle' },
  { id: '8', name: 'Myntra', logo: '👗', category: 'Fashion' },
  { id: '9', name: 'Flipkart', logo: '📦', category: 'Electronics' },
  { id: '10', name: 'IKEA', logo: '🪑', category: 'Lifestyle' },
  { id: '11', name: 'Adidas', logo: '⚽', category: 'Fashion' },
  { id: '12', name: 'Samsung', logo: '📱', category: 'Electronics' },
  { id: '13', name: 'MakeMyTrip', logo: '🏨', category: 'Travel' },
  { id: '14', name: 'Lululemon', logo: '🧘', category: 'Fashion' },
  { id: '15', name: 'Croma', logo: '🔌', category: 'Electronics' },
  { id: '16', name: 'Nykaa', logo: '💅', category: 'Lifestyle' },
  { id: '17', name: 'H&M', logo: '👕', category: 'Fashion' },
  { id: '18', name: 'Booking.com', logo: '🧳', category: 'Travel' },
  { id: '19', name: 'Decathlon', logo: '🏸', category: 'Lifestyle' },
  { id: '20', name: 'Dell', logo: '💻', category: 'Electronics' },
  { id: '21', name: 'Zara', logo: '🧥', category: 'Fashion' },
  { id: '22', name: 'Skyscanner', logo: '🌏', category: 'Travel' },
  { id: '23', name: 'Cult.fit', logo: '🏋️', category: 'Lifestyle' },
  { id: '24', name: 'OnePlus', logo: '🔴', category: 'Electronics' },
  { id: '25', name: 'Levis', logo: '👖', category: 'Fashion' },
  { id: '26', name: 'Agoda', logo: '🏖️', category: 'Travel' },
  { id: '27', name: 'Home Centre', logo: '🛋️', category: 'Lifestyle' },
  { id: '28', name: 'HP', logo: '🖱️', category: 'Electronics' },
  { id: '29', name: 'Puma', logo: '🐆', category: 'Fashion' },
  { id: '30', name: 'Airbnb', logo: '🏠', category: 'Travel' },
  { id: '31', name: 'Pepperfry', logo: '🖼️', category: 'Lifestyle' },
  { id: '32', name: 'Sony', logo: '🎮', category: 'Electronics' },
  { id: '33', name: 'Uniqlo', logo: '👘', category: 'Fashion' },
  { id: '34', name: 'Indigo', logo: '🛫', category: 'Travel' },
  { id: '35', name: 'Urban Company', logo: '🧹', category: 'Lifestyle' },
  { id: '36', name: 'Asus', logo: '🖥️', category: 'Electronics' },
  { id: '37', name: 'Reebok', logo: '🏃', category: 'Fashion' },
  { id: '38', name: 'Cleartrip', logo: '🗺️', category: 'Travel' },
  { id: '39', name: 'Pure Home', logo: '🕯️', category: 'Lifestyle' },
  { id: '40', name: 'Lenovo', logo: '⌨️', category: 'Electronics' },
  { id: '41', name: 'Lacoste', logo: '🐊', category: 'Fashion' },
  { id: '42', name: 'TripAdvisor', logo: '🦉', category: 'Travel' },
  { id: '43', name: 'Forest Essentials', logo: '🌿', category: 'Lifestyle' },
  { id: '44', name: 'Bose', logo: '🎧', category: 'Electronics' },
  { id: '45', name: 'Forever 21', logo: '🎀', category: 'Fashion' },
  { id: '46', name: 'Qatar Airways', logo: '✈️', category: 'Travel' },
  { id: '47', name: 'The Body Shop', logo: '🚿', category: 'Lifestyle' },
  { id: '48', name: 'Canon', logo: '📷', category: 'Electronics' },
  { id: '49', name: 'Under Armour', logo: '🎽', category: 'Fashion' },
  { id: '51', name: 'Emirates', logo: '🇦🇪', category: 'Travel' },
  { id: '52', name: 'Zomato', logo: '🛵', category: 'Food & Dining' },
  { id: '53', name: 'Swiggy', logo: '🥡', category: 'Food & Dining' },
  { id: '54', name: 'Starbucks', logo: '☕', category: 'Food & Dining' },
  { id: '55', name: 'Dominos', logo: '🍕', category: 'Food & Dining' },
  { id: '56', name: 'KFC', logo: '🍗', category: 'Food & Dining' },
  { id: '57', name: 'Pizza Hut', logo: '🍕', category: 'Food & Dining' },
  { id: '58', name: 'Subway', logo: '🥪', category: 'Food & Dining' },
  { id: '59', name: 'McDonalds', logo: '🍔', category: 'Food & Dining' },
  { id: '60', name: 'Whole Foods', logo: '🥬', category: 'Groceries' },
  { id: '61', name: 'BigBasket', logo: '🛒', category: 'Groceries' },
  { id: '62', name: 'Blinkit', logo: '⚡', category: 'Groceries' },
];

export const OFFERS: Offer[] = [
  { id: 'o1', merchantId: '1', cashbackPercentage: 5.5, description: 'Electronics Mega Sale', terms: ['Excludes Apple'], isFeatured: true },
  { id: 'o2', merchantId: '2', cashbackPercentage: 10, description: 'Nike Membership Week', terms: ['No minimum'], isFeatured: true, isLimitedTime: true, label: 'Early Access', expiresAt: '2026-05-03T18:00:00Z' },
  { id: 'o3', merchantId: '3', cashbackPercentage: 8, description: 'Summer Escape Deals', terms: ['Max ₹2000'] },
  { id: 'o4', merchantId: '4', cashbackPercentage: 3, description: 'Apple Student Discount', terms: ['Verified students only'], isLimitedTime: true, expiresAt: '2026-05-04T12:00:00Z' },
  { id: 'o5', merchantId: '5', cashbackPercentage: 7, description: 'Fashion Forward Offer', terms: ['Selected brands'] },
  { id: 'o6', merchantId: '6', cashbackPercentage: 12, description: 'Hotel Flash Sale', terms: ['Valid 48h'], isLimitedTime: true, label: 'Flash Sale', expiresAt: '2026-05-03T09:00:00Z' },
  { id: 'o7', merchantId: '7', cashbackPercentage: 6, description: 'Beauty Rewards Program', terms: ['All brands'] },
  { id: 'o8', merchantId: '8', cashbackPercentage: 18, description: 'Diwali Sparkle Sale', terms: ['No min purchase'], isFeatured: true, label: 'Festival Offer' },
  { id: 'o9', merchantId: '9', cashbackPercentage: 12, description: 'Big Billion Bonus', terms: ['Select sellers'], isFeatured: true, label: 'Festival Special' },
  { id: 'o10', merchantId: '10', cashbackPercentage: 5, description: 'Home Revamp Deals', terms: ['Valid on furniture'] },
  { id: 'o11', merchantId: '11', cashbackPercentage: 8, description: 'Sportswear Carnival', terms: ['Ends Sunday'], isLimitedTime: true },
  { id: 'o12', merchantId: '12', cashbackPercentage: 4, description: 'Samsung Galaxy Perks', terms: ['New launches only'] },
  { id: 'o13', merchantId: '13', cashbackPercentage: 10, description: 'Holi Holiday Bash', terms: ['Booking till March'], label: 'Festival Offer' },
  { id: 'o14', merchantId: '14', cashbackPercentage: 9, description: 'Yoga Month Special', terms: ['App exclusive'] },
  { id: 'o15', merchantId: '15', cashbackPercentage: 7, description: 'Gizmo Week', terms: ['Orders > ₹5000'] },
  { id: 'o16', merchantId: '16', cashbackPercentage: 11, description: 'Glamour Days', terms: ['Luxury brands included'], isFeatured: true },
  { id: 'o17', merchantId: '17', cashbackPercentage: 6, description: 'Style Upgrade', terms: ['Sustainability range'] },
  { id: 'o18', merchantId: '18', cashbackPercentage: 14, description: 'Globe Trotter Offer', terms: ['Confirmed stays only'], isLimitedTime: true, label: 'Limited Time' },
  { id: 'o19', merchantId: '19', cashbackPercentage: 5, description: 'Fit India Movement', terms: ['Fitness gear'] },
  { id: 'o20', merchantId: '20', cashbackPercentage: 4.5, description: 'XPS Premium Bonus', terms: ['Laptops only'] },
  { id: 'o21', merchantId: '21', cashbackPercentage: 7.5, description: 'Spring Collection', terms: ['No sale items'] },
  { id: 'o22', merchantId: '22', cashbackPercentage: 2, description: 'Flight Price Drop', terms: ['Domestic only'] },
  { id: 'o23', merchantId: '23', cashbackPercentage: 20, description: 'New Year Transformation', terms: ['Annual packs'], label: 'Festival Offer' },
  { id: 'o24', merchantId: '24', cashbackPercentage: 3.5, description: 'Never Settle Rewards', terms: ['Accessories excluded'] },
  { id: 'o25', merchantId: '25', cashbackPercentage: 12, description: 'Denim Days', terms: ['Buy 2 Get Cashback'] },
  { id: 'o26', merchantId: '26', cashbackPercentage: 13, description: 'Agoda VIP Deal', terms: ['Gold members'] },
  { id: 'o27', merchantId: '27', cashbackPercentage: 6.5, description: 'Living Room Glow', terms: ['Curated picks'] },
  { id: 'o28', merchantId: '28', cashbackPercentage: 5.5, description: 'Work From Home Sale', terms: ['Printers included'] },
  { id: 'o29', merchantId: '29', cashbackPercentage: 11, description: 'Speedster Rewards', terms: ['Running shoes'] },
  { id: 'o30', merchantId: '30', cashbackPercentage: 10, description: 'Christmas Getaway', terms: ['International only'], label: 'Festival Offer' },
  { id: 'o31', merchantId: '31', cashbackPercentage: 8.5, description: 'Furniture Fiesta', terms: ['Min ₹15000'] },
  { id: 'o32', merchantId: '32', cashbackPercentage: 5, description: 'PS5 Accessories Bonus', terms: ['Controllers and headsets'] },
  { id: 'o33', merchantId: '33', cashbackPercentage: 9.5, description: 'Winter Essentials', terms: ['Heattech range'] },
  { id: 'o34', merchantId: '34', cashbackPercentage: 6, description: 'Fly High Bonus', terms: ['Business class only'], isLimitedTime: true },
  { id: 'o35', merchantId: '35', cashbackPercentage: 15, description: 'Urban Ease Service', terms: ['Spa at home'], isFeatured: true },
  { id: 'o36', merchantId: '36', cashbackPercentage: 4, description: 'ROG Gaming Week', terms: ['Gaming laptops'] },
  { id: 'o37', merchantId: '37', cashbackPercentage: 10.5, description: 'Classics Reborn', terms: ['Legacy shoes'] },
  { id: 'o38', merchantId: '38', cashbackPercentage: 7, description: 'Weekend Explorer', terms: ['Hotel + Flight'] },
  { id: 'o39', merchantId: '39', cashbackPercentage: 12, description: 'Ambience Boost', terms: ['Home fragrance'] },
  { id: 'o40', merchantId: '40', cashbackPercentage: 3, description: 'ThinkPad Pro Rewards', terms: ['B2B orders'] },
  { id: 'o41', merchantId: '41', cashbackPercentage: 14, description: 'Elite Polo Days', terms: ['Selected stores'], isFeatured: true },
  { id: 'o42', merchantId: '42', cashbackPercentage: 5, description: 'Travel Reviewer Perk', terms: ['Verified users'] },
  { id: 'o43', merchantId: '43', cashbackPercentage: 20, description: 'Rakhi Gift Special', terms: ['Gift boxes only'], label: 'Festival Offer' },
  { id: 'o44', merchantId: '44', cashbackPercentage: 6.5, description: 'Audio Excellence', terms: ['Noise cancelling'] },
  { id: 'o45', merchantId: '45', cashbackPercentage: 16, description: 'Party Season Sale', terms: ['Dresses and tops'], isLimitedTime: true, label: 'Flash Sale' },
  { id: 'o46', merchantId: '46', cashbackPercentage: 8, description: 'Business Class Rewards', terms: ['Europe routes'] },
  { id: 'o47', merchantId: '47', cashbackPercentage: 9, description: 'Eco-Friendly Beauty', terms: ['Refill packs'] },
  { id: 'o48', merchantId: '48', cashbackPercentage: 5.5, description: 'Click & Save', terms: ['DSLR only'] },
  { id: 'o49', merchantId: '49', cashbackPercentage: 11.5, description: 'Train Like A Pro', terms: ['Tech gear'] },
  { id: 'o50', merchantId: '51', cashbackPercentage: 10, description: 'Ramadan Travels', terms: ['Global network'], label: 'Festival Offer' },
  { id: 'o51', merchantId: '52', cashbackPercentage: 25, description: 'Zomato Gold Bonus', terms: ['Selected cities'], label: 'Flash Sale' },
  { id: 'o52', merchantId: '53', cashbackPercentage: 20, description: 'Swiggy Weekend Bash', terms: ['No min entry'], isFeatured: true, label: 'Festival Offer' },
  { id: 'o53', merchantId: '54', cashbackPercentage: 15, description: 'Brewed Rewards', terms: ['Any size beverage'], isLimitedTime: true },
  { id: 'o54', merchantId: '60', cashbackPercentage: 5, description: 'Organic Essentials', terms: ['Fresh produce only'] },
  { id: 'o55', merchantId: '61', cashbackPercentage: 12, description: 'Pantry Stockup', terms: ['Min order ₹2000'], isFeatured: true },
  { id: 'o56', merchantId: '62', cashbackPercentage: 10, description: 'Lightning Grocery', terms: ['App exclusive'], isLimitedTime: true },
];

export const TRANSACTIONS: Transaction[] = [
  {
    id: 't1',
    merchantId: '1',
    amount: 15499,
    cashbackAmount: 852.44,
    status: 'Validating',
    date: '2026-04-28',
    estimatedPayoutDate: '2026-06-15',
    orderId: 'ORD-AMZ-992817345',
  },
  {
    id: 't2',
    merchantId: '2',
    amount: 5999,
    cashbackAmount: 599.9,
    status: 'Tracked',
    date: '2026-05-01',
    estimatedPayoutDate: '2026-07-01',
    orderId: 'ORD-NKE-112233445',
  },
  {
    id: 't3',
    merchantId: '4',
    amount: 79900,
    cashbackAmount: 2397,
    status: 'Payable',
    date: '2026-03-10',
    estimatedPayoutDate: '2026-04-10',
    orderId: 'ORD-APP-887766554',
  },
  {
    id: 't4',
    merchantId: '3',
    amount: 12450,
    cashbackAmount: 996,
    status: 'Confirmed',
    date: '2026-04-15',
    estimatedPayoutDate: '2026-05-20',
    orderId: 'ORD-EXP-334455667',
  },
  {
    id: 't5',
    merchantId: '52',
    amount: 1250,
    cashbackAmount: 312.5,
    status: 'Confirmed',
    date: '2026-05-01',
    estimatedPayoutDate: '2026-06-01',
    orderId: 'ORD-ZOM-556644332',
  },
  {
    id: 't6',
    merchantId: '61',
    amount: 2450,
    cashbackAmount: 294,
    status: 'Tracked',
    date: '2026-05-02',
    estimatedPayoutDate: '2026-07-02',
    orderId: 'ORD-BBK-778899001',
  },
  {
    id: 't7',
    merchantId: '8',
    amount: 3499,
    cashbackAmount: 629.82,
    status: 'Validating',
    date: '2026-04-29',
    estimatedPayoutDate: '2026-06-20',
    orderId: 'ORD-MYN-221133445',
  },
  {
    id: 't8',
    merchantId: '7',
    amount: 5400,
    cashbackAmount: 324,
    status: 'Issue',
    date: '2026-05-01',
    estimatedPayoutDate: '2026-06-01',
    orderId: 'ORD-SEP-445566778',
  },
  {
    id: 't9',
    merchantId: '10',
    amount: 45000,
    cashbackAmount: 2250,
    status: 'Confirmed',
    date: '2026-04-20',
    estimatedPayoutDate: '2026-06-05',
    orderId: 'ORD-IKE-889900112',
  },
  {
    id: 't10',
    merchantId: '16',
    amount: 1850,
    cashbackAmount: 203.5,
    status: 'Tracked',
    date: '2026-05-02',
    estimatedPayoutDate: '2026-07-02',
    orderId: 'ORD-NYK-776655443',
  },
  {
    id: 't11',
    merchantId: '54',
    amount: 450,
    cashbackAmount: 67.5,
    status: 'Payable',
    date: '2026-04-10',
    estimatedPayoutDate: '2026-05-10',
    orderId: 'ORD-SBUX-1122334',
  },
  {
    id: 't12',
    merchantId: '21',
    amount: 8900,
    cashbackAmount: 667.5,
    status: 'Validating',
    date: '2026-04-30',
    estimatedPayoutDate: '2026-06-25',
    orderId: 'ORD-ZARA-9900112',
  },
];
